name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v4.1.1

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 4.234.160.181 >> ~/.ssh/known_hosts

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: krahristov
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t krahristov/construction-fe:latest .
          docker push krahristov/construction-fe:latest

      - name: Copy deployment script

        run: |
          scp -o StrictHostKeyChecking=no scripts/deploy_script_construction-fe.sh azureuser@4.234.160.181:~

      - name: Run deployment script
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@4.234.160.181 "\
          ls -l ~/deploy_script_construction-fe.sh && \
          chmod +x ~/deploy_script_construction-fe.sh && \
          bash ~/deploy_script_construction-fe.sh"